---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dspipelines.opendatahub.io
  resources:
  - dspipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dspipelines.opendatahub.io
  resources:
  - dspipelines/finalizers
  verbs:
  - update
- apiGroups:
  - dspipelines.opendatahub.io
  resources:
  - dspipelines/status
  verbs:
  - get
  - patch
  - update
